# JSON feeds are generated by Node.JS app located at:
# https://github.com/BMJ-Ltd/group/tree/headless/web/nodejs/ga2/ga2json
# run the apps "npm run start"

curl -o ../data/bmj-realtime.json --insecure https://localhost:2002/realtime/bmjsite?filter=content
curl -o ../data/bmjopen-last30days.json --insecure  -g 'https://localhost:2002/bmjsite?filter=content.*[a-z][a-z]*[0-9][0-9]*&site=34866726'